#!/bin/sh
uses(){
	echo -e 'using\n$0 file_codeswarm.xml'
}

generatelog(){
	echo "genereting... "
	state=("\\" "|" "/" "—")
	i=0
	if [ -f "$1" ]; then
		result=${1%.*}'.log'
		echo -n > $result
		#Выводим только строки в которых есть слово event
		grep -e "event " $1 | \
		#удаляем все символы табуляции и пробелы
		#удаляем все <event и />
		sed -e "s/^[ 	]*//;s/^<event //g;s|/>$||g" | \
		while read line
		do
			date=""
			#валидируем строку, появляются 4 переменные
			eval $line;
			#проверяем не пустали переменная date, если нет производим вывод
			[ -n "$date" ] && [ "`echo -n $data | wc -c`" -gt "10" ] && date=`echo $data | sed -e "s/^\(.\{10\}\).*/\1/"`
			[ -n "$date" ] && echo "$date|$author|$action|$filename" >> $result
			#отображение процесса генерации.
			echo -ne "\b${state[$i]}"
			(( i += 1 ))
			[[ $i -eq 5 ]] && i=0
		done 
		echo -ne "\bcompleted!"
	else
		echo -e "file log code_swarm not exsits!\n$1"
	fi
}

[ -n "$1" ] && generatelog $1 || uses 