#!/bin/sh

generate() {
	if test -t 1; then
		exec >$logfile
	fi

	echo -e "<?xml version=\"1.0\"?>\n<file_events>"
	echo "generating ..." >&2
	allline=`sed -n $= $gitdiff`

	awk -v alll=$allline '
		BEGIN {
			split(". .. ... .... ..... - -- --- ---- ------ = == === ==== =====", st, " ")
			ist=0
			pres=100/alll;
		}

		/^[0-9]/ {
			u=$0
			d=$0
			sub(/:.*/, "", d);
			sub(/[^:]*:/, "", u);
			next;
		}
		/^[ACDMRTUXB]/ {
			a=substr($0, 0, 1)
			sub(/[ACDMRTUXB]/, "")
			if (length($0) > 0){
				print "<event date=\""d"\" author=\""u"\" filename=\""$0"\" action=\""a"\"  comment=\"\"/>"
			}
			cmd = "echo -ne \"\\r                               \\r" FNR "/" alll "(" FNR * pres "%) " st[ist++] "\" >&2"
			#eсли запускать под debian, то
			#cmd = "bash -c \"echo -ne \\\"\\\\r                               \\\\r" FNR "/" alll "(" FNR * pres "%) " st[ist++] "\\\" >&2\""
			system(cmd)
			close(cmd)
			if (ist > 16) ist=0
		}
	' $gitdiff
	
	echo -ne "\r                               \r$allline/$allline (100%)" >&2
	echo -e "\n\1 completed \2" >&2
	echo "</file_events>"
	rm $gitdiff
}

prepare_git() {
	git log --name-status --reverse --pretty="%at000:$1" $2 | \
		grep -v "^[ \\t]*$" | \
		sed -e "s/^\([ACDMRTUXB]\)[ \\t]\+/\1/g" > $gitdiff
}

fileaction="$(date +%j%H%M%s)"

n=0
e=0
username=""

for arg
do
	case "$arg" in
		-n)			
			[[ $n -eq 0 ]] && username="%cn"$username
			n=1
		;;
		-e)
			[[ $e -eq 0 ]] && username=$username"%ce"
			e=1
		;;
		-en)
			e=1
			n=1
			username="&lt;%ce&gt; %cn"
		;;
		-ne)
			e=1
			n=1
			username="%cn &lt;%ce&gt;>"
		;;
		-[0-9])
			countcommit=$arg
		;;
	esac
done;

[ -n "$username" ] || username="%cn" 

echo -n "Будет использован лимит: " >&2
[ -n "$countcommit" ] && echo $countcommit' коммитов' >&2 || echo "все коммиты" >&2
echo -n "Шаблон имени пользователя: " >&2
echo $username >&2
echo -n >&2

gitdiff=$fileaction".temp"
logfile=$fileaction"action.xml"

prepare_git "$username" $countcommit
generate
