#!/bin/sh

generate() {
	if test -t 1; then
		exec >$logfile
	fi

	echo -e "<?xml version=\"1.0\"?>\n<file_events>"
	echo "generating ..." >&2

	awk -v typegen=$1 '
		BEGIN {
			split("\b\b\b\b\b. . . . . \b- \b\b- \b\b- \b\b- \b\b- \b= = = = =", st, " ")
			ist=0
			_ord_init()

			typehash=0
			if( typegen == "ch_code") {
				typehash=1
			}
			else if( typegen == "crypt" ) {
				typehash=2
			}
		}

		function _ord_init(low, high, i, t)
		{
			low = sprintf("%c", 7)
			if (low == "\a") {
				low = 0
				high = 127
			} else if (sprintf("%c", 128 + 7) == "\a") {
				low = 128
				high = 255
			} else {
				low = 0
				high = 255
			}

			for (i = low; i <= high; i++) {
				t = sprintf("%c", i)
				_ord_[t] = i
			}
		}

		function ord(str, c) {
			c = substr(str, 1, 1);
			return _ord_[c];
		}

		/^[0-9]/ { 
			sub(/:.*/, "");
			d=$0;
			next;
		}
		/^&/ {
			sub(/&/, "");
			f=$0
			substr($0, 2, length($0) - 1);
			next;
		}
		/^+/ { a="A"; }
		/^-/ { a="D"; }
		/^[\+-]/ {
			sub(/[\+-]/, "")
			str=""
			if( typehash == 1) {
				for(i=1; i<length($0); i++){
					str = str "" ord(substr($0, i, 1))
				}
				gsub(/32|16/, "/sd", str)
			}
			else {
				cmd="echo \"" $0 "\" | md5sum | cut -f1 -d \" \" | sed -e \"s@[32|16]@/sd@g;\" -e \"s/\\(..\\)\$/.\\1/\"" 
				if ( typehash == 2 )
					cmd="C:/Perl/bin/perl -e \"print crypt($ARGV[0], $ARGV[1])\" \"" $0 "\" \"1/5l58j/jk\"" 
				cmd | getline str;
				close(cmd);
			}

			if (str != "")
				print "<event date=\""d"\" author=\""f"\" filename=\""str"\" action=\""a"\"  comment=\"\"/>"
				
			system("echo -ne \"" st[ist++] "\" >&2")
			if (ist > 16) ist=0
		}
	' $gitdiff

	echo -ne "\b\b\b\b\b\b\b\b\b\b\b\bcompleted!" >&2
	echo "</file_events>"
	rm $gitdiff
}

prepare_git() {
    git log -U0 --diff-filter=AMD --reverse --pretty="%at000:%cn" $1 | \
        grep -v "^\(-\{3\}\|+\{3\}\) " | \
        grep -v "^[+-][ 	]*$" | \
        grep -v "^[+-]$" | \
        grep -v "^[ 	]*$" | \
        sed -e "s/diff .* b\//\&/g" \
            -e "s/^+[ 	]\+/+/g" \
            -e "s/^-[ 	]\+/-/g" \
            -e "s/[ 	]\+$//g" \
            -e "s/^$//g" \
            -e 's/\\/\\\\/g' \
            -e "s/[\"\`<>$]//g" > $gitdiff
}

fileaction="$(date +%j%H%M%s)"

[ -n "$1" ] && countcommit=$1 || echo -e "первым параметром передаетс€ лимит коммитов\n" + \
    "git log --help\nпараметер:\t-<n>\n\t\tLimits the number of commits to show.\nusing: $0 -10" >&2
echo -n "Ѕудет использован лимит: " >&2
[ -n "$1" ] && echo $1' коммитов' >&2 || echo "все коммиты" >&2

typehash=md5
[ -n "$2" ] && typehash=$2 || echo -e "вторым параметром передаетс€ тип функции дл€" + \
    "генерации хеша строки\nдоступны следующие значени€:\n" + \
    "\t\tmd5 Ч по-умолчанию\n\t\tcrypt\n\t\tch_code\nusing: $0 -10 crypt" >&2
echo "Ѕудет применена функци€: "$typehash >&2

gitdiff=$fileaction".temp"
logfile=$fileaction"action.xml"

prepare_git $countcommit
generate $typehash